### PR TITLE
fix: aligned powered by text in search popup

### LINKED ISSUE #269: Footer `Powered by` is at the bottom right instead of bottom left
Currently, `Powered by` is at the bottom left of the popup. It should be next to `Meilisearch`. 

Screenshot 2022-10-17 at 13 33 26

### PR DESCRIPTION
**Pull request by bhanuloshali1995**
# Pull Request

## Related issue
Fixes #269 

## What does this PR do?
- Aligns the search popup's bottom **Powered By** text to the right.

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

File: MeiliSearchBox.vue [hunk 1]
```diff
@@ -207,8 +207,9 @@ dark-input()
     // Footer
     .docs-searchbar-footer
       display flex 
-      justify-content space-between 
-      align-items center 
+      justify-content flex-end 
+      align-items center
+      column-gap 10px
```
Comment (bidoubiwa) [inline MeiliSearchBox.vue:212]: There is still a gap between the text and the logo. I think if we just remove all these lines, it works

**Review by bidoubiwa — CHANGES_REQUESTED** [review]

File: MeiliSearchBox.vue (hunk 1 above)
Comment (bhanuloshali1995) [reply MeiliSearchBox.vue:212]: It won't work if we remove all these lines. The issue was because of **justify-content space-between**.

The little space is because of **column-gap 10px**. I don't know if it would look good if all the space is removed but if you want 0 space let me know. I'll remove the 10px gap b/w the text and logo.

Comment (bidoubiwa) [reply MeiliSearchBox.vue:212]: Did you remove `display flex` as well? I tried it locally and it seems to work

Comment (bidoubiwa) [reply MeiliSearchBox.vue:212]: Screenshot 2022-10-27 at 11 16 21
Screenshot 2022-10-27 at 11 16 42

Comment (bhanuloshali1995) [reply MeiliSearchBox.vue]: Oh, flex was there. I have updated the PR. Thanks.

**Comment by bidoubiwa** [comment]
bors merge

**Comment by bidoubiwa** [comment]
bors merge
